[phases.setup]
nixPkgs = ['nodejs', 'pkg-config', 'openssl']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'

[variables]
NODE_ENV = 'production'
NIXPACKS_PLATFORM = 'linux/amd64'
