[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = ['pwd', 'yarn install']

[phases.build]
cmds = ['pwd', 'yarn mastra build']

[start]
cmd = 'pwd && yarn start'

[variables]
NODE_ENV = 'production'
